"""ML Model Monitoring via Cortex Agent.

This module provides a complete monitoring system for Many-Model Training deployments:

1. Statistical drift detection (SQL-based, no LLM needed)
2. Feature distribution analysis (compares recent vs historical)
3. Prediction bias detection (waste/lost-sales opportunities)
4. Cortex Agent creation (with Analyst + Search tools for interactive monitoring)
5. Agent-powered synthesis (queries the agent for root cause analysis)

The Cortex Agent is configured with:
- cortex_analyst_text_to_sql: queries telemetry, model catalog, and experiment data
- cortex_search: retrieves past insights and recommendations for context
"""
from snowflake.snowpark import Session
import snowflake.snowpark.functions as F
from datetime import datetime
import json
import numpy as np
from utils import create_session, get_feature_config, get_fully_qualified_name, get_telemetry_config


feature_cfg = get_feature_config()
telemetry_cfg = get_telemetry_config()

GRAIN = feature_cfg["partition_col"]
TARGET = feature_cfg["target_col"]
TIME = feature_cfg["time_col"]

AGENT_NAME = "MMT_MONITORING_AGENT"


# =============================================================================
# Infrastructure Setup
# =============================================================================

def create_insights_table(session: Session):
    """Create AGENT_INSIGHTS table if not exists."""
    fqn = get_fully_qualified_name("AGENT_INSIGHTS")
    session.sql(f"""
        CREATE TABLE IF NOT EXISTS {fqn} (
            INSIGHT_ID VARCHAR,
            CREATED_AT TIMESTAMP_NTZ,
            CATEGORY VARCHAR,
            STORE_ITEM_ID VARCHAR,
            SUMMARY VARCHAR,
            DETAIL VARCHAR(4000),
            RECOMMENDATION VARCHAR(2000),
            STATUS VARCHAR DEFAULT 'new',
            METADATA VARIANT
        )
    """).collect()
    print("   AGENT_INSIGHTS table ready")


def create_monitoring_agent(session: Session):
    """Create the Cortex Agent for ML model monitoring.

    The agent has two tools:
    - cortex_analyst_text_to_sql: queries telemetry via a semantic view
    - cortex_search: retrieves past insights for context

    Prerequisites: run setup.sql first to create the semantic view and search service.
    """
    conn_cfg = get_feature_config()
    db = "MMT_DEMO"
    schema = "FORECASTING"

    agent_spec = f"""
models:
  orchestration: auto

orchestration:
  budget:
    seconds: 45
    tokens: 16000

instructions:
  response: |
    You are an ML operations monitoring agent for a retail demand forecasting system.
    You monitor {GRAIN} partition-level models and provide actionable insights.
    When analyzing drift, always:
    1. Identify WHICH partitions are affected (cite specific store-item IDs)
    2. Quantify HOW BAD the degradation is (MAPE values, error magnitudes)
    3. Explain WHY it likely happened (feature shifts, seasonal changes, data issues)
    4. Recommend WHAT TO DO (retrain, investigate, add features, wait)
    Be specific and data-driven. Reference actual numbers from the telemetry data.
  orchestration: |
    For questions about model performance, drift, predictions, or experiments, use the
    telemetry_analyst tool to query the underlying data.
    For questions about past recommendations, historical patterns, or previous analyses,
    use the insights_search tool to find relevant past insights.
    Always check telemetry data before making recommendations.
  sample_questions:
    - question: "Which models are currently drifting and why?"
    - question: "What is the average MAPE across all partitions this week?"
    - question: "Which partitions should we retrain and what features should we add?"
    - question: "Are there any systematic over-prediction or under-prediction patterns?"

tools:
  - tool_spec:
      type: "cortex_analyst_text_to_sql"
      name: "telemetry_analyst"
      description: >
        Queries ML model telemetry data including: forecast accuracy (MAPE, MAE) per
        store-item partition, drift flags, prediction errors, model catalog metadata
        (training dates, hyperparameters, feature versions), and experiment results
        (champion vs challenger comparisons). Use this tool to answer any quantitative
        question about model performance, drift detection, or experiment outcomes.
  - tool_spec:
      type: "cortex_search"
      name: "insights_search"
      description: >
        Searches historical monitoring insights and recommendations. Contains past
        drift analyses, root cause explanations, and action items generated by
        previous monitoring cycles. Use this tool to find context about recurring
        issues, past recommendations for specific partitions, or historical patterns.

tool_resources:
  telemetry_analyst:
    semantic_view: "{db}.{schema}.MMT_TELEMETRY_VIEW"
  insights_search:
    name: "{db}.{schema}.INSIGHTS_SEARCH_SVC"
    max_results: "10"
    title_column: "SUMMARY"
    id_column: "INSIGHT_ID"
"""

    session.sql(f"""
        CREATE OR REPLACE AGENT {db}.{schema}.{AGENT_NAME}
        COMMENT = 'ML model monitoring agent for demand forecasting MMT deployment'
        FROM SPECIFICATION
        $${agent_spec}$$
    """).collect()

    print(f"   Agent created: {db}.{schema}.{AGENT_NAME}")
    print(f"   Tools: telemetry_analyst (Cortex Analyst), insights_search (Cortex Search)")


def query_monitoring_agent(session: Session, question: str) -> str:
    """Query the monitoring agent with a natural language question.

    Args:
        question: Natural language question about model performance, drift, etc.

    Returns:
        Agent's response as a string.
    """
    db = "MMT_DEMO"
    schema = "FORECASTING"

    result = session.sql(f"""
        SELECT SNOWFLAKE.CORTEX.AGENT(
            '{db}.{schema}.{AGENT_NAME}',
            '{question.replace("'", "''")}'
        ):content::VARCHAR AS RESPONSE
    """).collect()

    return result[0]["RESPONSE"] if result else "No response from agent."


# =============================================================================
# Statistical Analysis (runs without LLM — pure SQL/Python)
# =============================================================================

def detect_drifting_partitions(session: Session) -> list:
    """Identify partitions where rolling MAPE exceeds threshold."""
    telemetry_fqn = get_fully_qualified_name("FORECAST_TELEMETRY")

    drifting = session.sql(f"""
        SELECT {GRAIN},
               MAX(ROLLING_7D_MAPE) AS CURRENT_MAPE,
               COUNT(*) AS OBSERVATION_COUNT,
               AVG(ABS(ERROR)) AS AVG_ABS_ERROR,
               STDDEV(ERROR) AS ERROR_VOLATILITY
        FROM {telemetry_fqn}
        WHERE DRIFT_FLAG = TRUE
        GROUP BY {GRAIN}
        ORDER BY CURRENT_MAPE DESC
        LIMIT {telemetry_cfg.get('alert_top_n', 20)}
    """).collect()

    return [dict(row) for row in drifting]


def analyze_feature_distributions(session: Session, drifting_partitions: list) -> list:
    """Compare recent vs historical feature distributions for drifting partitions.

    For each drifting partition, computes:
    - Mean shift per feature (recent 7 days vs prior history)
    - Identifies which features shifted most significantly
    """
    feature_fqn = get_fully_qualified_name("FEATURE_TABLE")

    analyses = []
    for partition in drifting_partitions[:10]:
        partition_id = partition[GRAIN]
        try:
            # Recent 7 days vs all prior data
            comparison = session.sql(f"""
                WITH recent AS (
                    SELECT
                        AVG(WEATHER_TEMP) AS AVG_TEMP,
                        AVG(CASE WHEN IS_HOLIDAY THEN 1 ELSE 0 END) AS HOLIDAY_RATE,
                        AVG(CASE WHEN IS_WEEKEND THEN 1 ELSE 0 END) AS WEEKEND_RATE,
                        AVG(CASE WHEN EVENT_FLAG THEN 1 ELSE 0 END) AS EVENT_RATE,
                        AVG(ROLLING_7D_AVG) AS AVG_ROLLING_7D,
                        AVG(DEMAND) AS AVG_DEMAND
                    FROM {feature_fqn}
                    WHERE {GRAIN} = '{partition_id}'
                      AND {TIME} >= DATEADD(day, -7, (SELECT MAX({TIME}) FROM {feature_fqn}))
                ),
                historical AS (
                    SELECT
                        AVG(WEATHER_TEMP) AS AVG_TEMP,
                        AVG(CASE WHEN IS_HOLIDAY THEN 1 ELSE 0 END) AS HOLIDAY_RATE,
                        AVG(CASE WHEN IS_WEEKEND THEN 1 ELSE 0 END) AS WEEKEND_RATE,
                        AVG(CASE WHEN EVENT_FLAG THEN 1 ELSE 0 END) AS EVENT_RATE,
                        AVG(ROLLING_7D_AVG) AS AVG_ROLLING_7D,
                        AVG(DEMAND) AS AVG_DEMAND
                    FROM {feature_fqn}
                    WHERE {GRAIN} = '{partition_id}'
                      AND {TIME} < DATEADD(day, -7, (SELECT MAX({TIME}) FROM {feature_fqn}))
                )
                SELECT
                    r.AVG_TEMP AS RECENT_TEMP, h.AVG_TEMP AS HIST_TEMP,
                    r.HOLIDAY_RATE AS RECENT_HOLIDAY, h.HOLIDAY_RATE AS HIST_HOLIDAY,
                    r.WEEKEND_RATE AS RECENT_WEEKEND, h.WEEKEND_RATE AS HIST_WEEKEND,
                    r.EVENT_RATE AS RECENT_EVENT, h.EVENT_RATE AS HIST_EVENT,
                    r.AVG_ROLLING_7D AS RECENT_ROLLING, h.AVG_ROLLING_7D AS HIST_ROLLING,
                    r.AVG_DEMAND AS RECENT_DEMAND, h.AVG_DEMAND AS HIST_DEMAND
                FROM recent r, historical h
            """).collect()

            feature_shifts = {}
            if comparison:
                row = comparison[0]
                # Temperature shift
                if row["RECENT_TEMP"] is not None and row["HIST_TEMP"] is not None:
                    temp_diff = abs(float(row["RECENT_TEMP"]) - float(row["HIST_TEMP"]))
                    if temp_diff > 15:
                        feature_shifts["WEATHER_TEMP"] = {
                            "recent": round(float(row["RECENT_TEMP"]), 1),
                            "historical": round(float(row["HIST_TEMP"]), 1),
                            "shift": round(temp_diff, 1),
                            "description": f"Temperature shifted from {float(row['HIST_TEMP']):.0f}F to {float(row['RECENT_TEMP']):.0f}F"
                        }
                # Event rate shift
                if row["RECENT_EVENT"] is not None and row["HIST_EVENT"] is not None:
                    event_diff = float(row["RECENT_EVENT"]) - float(row["HIST_EVENT"])
                    if abs(event_diff) > 0.1:
                        feature_shifts["EVENT_FLAG"] = {
                            "recent": round(float(row["RECENT_EVENT"]), 3),
                            "historical": round(float(row["HIST_EVENT"]), 3),
                            "shift": round(event_diff, 3),
                            "description": f"Event rate {'increased' if event_diff > 0 else 'decreased'} from {float(row['HIST_EVENT']):.1%} to {float(row['RECENT_EVENT']):.1%}"
                        }
                # Demand level shift (target drift)
                if row["RECENT_DEMAND"] is not None and row["HIST_DEMAND"] is not None:
                    demand_pct_change = (float(row["RECENT_DEMAND"]) - float(row["HIST_DEMAND"])) / max(float(row["HIST_DEMAND"]), 1)
                    if abs(demand_pct_change) > 0.2:
                        feature_shifts["DEMAND_LEVEL"] = {
                            "recent": round(float(row["RECENT_DEMAND"]), 1),
                            "historical": round(float(row["HIST_DEMAND"]), 1),
                            "shift_pct": round(demand_pct_change * 100, 1),
                            "description": f"Demand level shifted {demand_pct_change*100:.0f}% (from {float(row['HIST_DEMAND']):.1f} to {float(row['RECENT_DEMAND']):.1f} units/hr)"
                        }
        except Exception:
            feature_shifts = {}

        analyses.append({
            "partition_id": partition_id,
            "current_mape": partition.get("CURRENT_MAPE"),
            "feature_shifts": feature_shifts,
            "num_features_shifted": len(feature_shifts),
        })

    return analyses


def detect_prediction_bias(session: Session) -> dict:
    """Detect systematic over/under-prediction patterns across partitions."""
    telemetry_fqn = get_fully_qualified_name("FORECAST_TELEMETRY")

    # Over-predicting partitions (waste)
    over_pred = session.sql(f"""
        SELECT {GRAIN}, AVG(ERROR) AS AVG_BIAS, COUNT(*) AS N,
               STDDEV(ERROR) AS BIAS_VOLATILITY
        FROM {telemetry_fqn}
        WHERE ERROR > 0
        GROUP BY {GRAIN}
        HAVING AVG(ERROR) > 3 AND COUNT(*) > 100
        ORDER BY AVG_BIAS DESC
        LIMIT 5
    """).collect()

    # Under-predicting partitions (lost sales)
    under_pred = session.sql(f"""
        SELECT {GRAIN}, AVG(ERROR) AS AVG_BIAS, COUNT(*) AS N,
               STDDEV(ERROR) AS BIAS_VOLATILITY
        FROM {telemetry_fqn}
        WHERE ERROR < 0
        GROUP BY {GRAIN}
        HAVING AVG(ERROR) < -3 AND COUNT(*) > 100
        ORDER BY AVG_BIAS ASC
        LIMIT 5
    """).collect()

    return {
        "waste_risk": [
            {
                "partition_id": row[GRAIN],
                "avg_over_prediction": round(float(row["AVG_BIAS"]), 1),
                "observations": int(row["N"]),
            }
            for row in over_pred
        ],
        "lost_sales_risk": [
            {
                "partition_id": row[GRAIN],
                "avg_under_prediction": round(abs(float(row["AVG_BIAS"])), 1),
                "observations": int(row["N"]),
            }
            for row in under_pred
        ],
    }


def compute_fleet_summary(session: Session) -> dict:
    """Compute fleet-wide health summary statistics."""
    telemetry_fqn = get_fully_qualified_name("FORECAST_TELEMETRY")

    summary = session.sql(f"""
        SELECT
            COUNT(DISTINCT {GRAIN}) AS TOTAL_PARTITIONS,
            COUNT(DISTINCT CASE WHEN DRIFT_FLAG = TRUE THEN {GRAIN} END) AS DRIFTING_PARTITIONS,
            AVG(ROLLING_7D_MAPE) AS AVG_FLEET_MAPE,
            MEDIAN(ROLLING_7D_MAPE) AS MEDIAN_FLEET_MAPE,
            MAX(ROLLING_7D_MAPE) AS WORST_MAPE,
            AVG(ABS(ERROR)) AS AVG_ABS_ERROR
        FROM {telemetry_fqn}
        WHERE ROLLING_7D_MAPE IS NOT NULL
    """).collect()

    if summary:
        row = summary[0]
        return {
            "total_partitions": int(row["TOTAL_PARTITIONS"] or 0),
            "drifting_partitions": int(row["DRIFTING_PARTITIONS"] or 0),
            "drifting_pct": round(int(row["DRIFTING_PARTITIONS"] or 0) / max(int(row["TOTAL_PARTITIONS"] or 1), 1) * 100, 1),
            "avg_fleet_mape": round(float(row["AVG_FLEET_MAPE"] or 0), 4),
            "median_fleet_mape": round(float(row["MEDIAN_FLEET_MAPE"] or 0), 4),
            "worst_mape": round(float(row["WORST_MAPE"] or 0), 4),
            "avg_abs_error": round(float(row["AVG_ABS_ERROR"] or 0), 2),
        }
    return {}


# =============================================================================
# LLM Synthesis (uses AI_COMPLETE for cases without agent, or the agent itself)
# =============================================================================

def synthesize_with_llm(session: Session, drift_analysis: list, bias_analysis: dict,
                        fleet_summary: dict) -> str:
    """Use AI_COMPLETE to synthesize statistical findings into a monitoring report.

    This is the fallback when the full Cortex Agent isn't set up yet.
    Passes structured analysis data to the LLM for natural-language synthesis.
    """
    analysis_payload = json.dumps({
        "fleet_summary": fleet_summary,
        "drifting_partitions": drift_analysis[:5],
        "prediction_bias": bias_analysis,
    }, indent=2, default=str)

    prompt = f"""You are an ML operations analyst for a retail demand forecasting system
with {fleet_summary.get('total_partitions', 0)} partition-level models.

Here is the latest monitoring analysis:

{analysis_payload}

Provide a structured monitoring report with:
1. FLEET HEALTH: One-paragraph summary of overall fleet health
2. TOP DRIFT ISSUES: For each drifting partition, explain the likely cause based on feature shifts
3. BIAS PATTERNS: Summarize any systematic over/under-prediction and business impact
4. RECOMMENDED ACTIONS: Prioritized list of 3-5 specific actions (retrain X, investigate Y, add feature Z)

Be specific — cite partition IDs, MAPE values, and feature shift magnitudes."""

    try:
        result = session.sql(f"""
            SELECT AI_COMPLETE('mistral-large2', $${prompt}$$) AS RESPONSE
        """).collect()
        return result[0]["RESPONSE"]
    except Exception as e:
        return f"AI_COMPLETE unavailable ({e}). Raw analysis:\n{analysis_payload}"


# =============================================================================
# Main Monitoring Cycle
# =============================================================================

def run_monitoring_cycle(session: Session = None, write_insights: bool = True,
                         use_agent: bool = False):
    """Full monitoring cycle: detect → analyze → synthesize → store.

    Steps:
    1. Compute fleet-wide health summary
    2. Detect drifting partitions (SQL-based, threshold from config)
    3. Analyze feature distributions for drifting partitions
    4. Detect prediction bias patterns (waste/lost-sales)
    5. Synthesize findings via Cortex Agent or AI_COMPLETE fallback
    6. Store insights to AGENT_INSIGHTS table

    Args:
        use_agent: If True, queries the Cortex Agent for synthesis.
                   If False, uses AI_COMPLETE directly with the structured analysis.
    """
    if session is None:
        session = create_session("agent_monitor")
        print(f"Connected: {session.get_current_account()}")

    print("=" * 60)
    print("ML MODEL MONITORING CYCLE")
    print("=" * 60)

    create_insights_table(session)
    insights_fqn = get_fully_qualified_name("AGENT_INSIGHTS")

    # Step 1: Fleet summary
    print("\n   [1/5] Computing fleet health summary...")
    fleet_summary = compute_fleet_summary(session)
    print(f"   Fleet: {fleet_summary.get('total_partitions', 0)} partitions, "
          f"{fleet_summary.get('drifting_partitions', 0)} drifting "
          f"({fleet_summary.get('drifting_pct', 0)}%)")
    print(f"   Avg MAPE: {fleet_summary.get('avg_fleet_mape', 0):.2%}, "
          f"Worst: {fleet_summary.get('worst_mape', 0):.2%}")

    # Step 2: Detect drift
    print("\n   [2/5] Detecting drifting partitions...")
    drifting = detect_drifting_partitions(session)

    if not drifting:
        print("   All models performing within threshold. No action needed.")
        return {"fleet_summary": fleet_summary, "insights": []}

    print(f"   Found {len(drifting)} partitions exceeding drift threshold")

    # Step 3: Feature distribution analysis
    print("\n   [3/5] Analyzing feature distributions...")
    drift_analyses = analyze_feature_distributions(session, drifting)
    shifted_count = sum(1 for a in drift_analyses if a["num_features_shifted"] > 0)
    print(f"   {shifted_count}/{len(drift_analyses)} partitions show feature distribution shifts")

    # Step 4: Bias detection
    print("\n   [4/5] Detecting prediction bias patterns...")
    bias = detect_prediction_bias(session)
    print(f"   Waste risk (over-prediction): {len(bias['waste_risk'])} partitions")
    print(f"   Lost sales risk (under-prediction): {len(bias['lost_sales_risk'])} partitions")

    # Step 5: Synthesis
    print("\n   [5/5] Generating monitoring report...")
    if use_agent:
        question = (
            f"We have {len(drifting)} drifting partitions with the worst MAPE at "
            f"{fleet_summary.get('worst_mape', 0):.1%}. "
            f"Feature analysis shows {shifted_count} partitions with distribution shifts. "
            f"What are the root causes and what should we do?"
        )
        report = query_monitoring_agent(session, question)
    else:
        report = synthesize_with_llm(session, drift_analyses, bias, fleet_summary)

    print(f"\n{'─' * 60}")
    print("MONITORING REPORT")
    print(f"{'─' * 60}")
    print(report)

    # Store insights
    if write_insights:
        for analysis in drift_analyses:
            partition_id = analysis["partition_id"]
            shifts_desc = "; ".join(
                s["description"] for s in analysis["feature_shifts"].values()
            ) if analysis["feature_shifts"] else "No clear feature shift detected"

            summary = f"Drift detected: MAPE {float(analysis['current_mape']):.1%} (threshold: {telemetry_cfg['drift_threshold_mape']:.0%})"
            detail = f"Partition {partition_id} exceeded drift threshold. Feature analysis: {shifts_desc}"
            recommendation = "Query the monitoring agent for detailed root cause analysis and recommended actions."

            session.sql(f"""
                INSERT INTO {insights_fqn}
                (INSIGHT_ID, CREATED_AT, CATEGORY, STORE_ITEM_ID, SUMMARY, DETAIL, RECOMMENDATION, STATUS, METADATA)
                SELECT UUID_STRING(), CURRENT_TIMESTAMP(), 'drift', '{partition_id}',
                       '{summary.replace("'", "''")}',
                       '{detail.replace("'", "''")}',
                       '{recommendation.replace("'", "''")}',
                       'new',
                       PARSE_JSON('{json.dumps(analysis["feature_shifts"], default=str).replace("'", "''")}')
            """).collect()

        for opp in bias["waste_risk"]:
            session.sql(f"""
                INSERT INTO {insights_fqn}
                (INSIGHT_ID, CREATED_AT, CATEGORY, STORE_ITEM_ID, SUMMARY, DETAIL, RECOMMENDATION, STATUS)
                SELECT UUID_STRING(), CURRENT_TIMESTAMP(), 'waste_reduction', '{opp["partition_id"]}',
                       'Over-predicting by {opp["avg_over_prediction"]:.1f} units/hr',
                       'Systematic over-prediction detected over {opp["observations"]} observations. Potential inventory waste.',
                       'Investigate demand patterns and consider retraining with recent data emphasis.',
                       'new'
            """).collect()

        for opp in bias["lost_sales_risk"]:
            session.sql(f"""
                INSERT INTO {insights_fqn}
                (INSIGHT_ID, CREATED_AT, CATEGORY, STORE_ITEM_ID, SUMMARY, DETAIL, RECOMMENDATION, STATUS)
                SELECT UUID_STRING(), CURRENT_TIMESTAMP(), 'lost_sales', '{opp["partition_id"]}',
                       'Under-predicting by {opp["avg_under_prediction"]:.1f} units/hr',
                       'Systematic under-prediction detected over {opp["observations"]} observations. Potential lost revenue.',
                       'Consider increasing forecast bias or retraining with recent demand uplift.',
                       'new'
            """).collect()

        total_insights = len(drift_analyses) + len(bias["waste_risk"]) + len(bias["lost_sales_risk"])
        print(f"\n   {total_insights} insights written to AGENT_INSIGHTS")

    return {
        "fleet_summary": fleet_summary,
        "drifting": drift_analyses,
        "bias": bias,
        "report": report,
    }


def get_recent_insights(session: Session, limit: int = 20) -> list:
    """Return recent insights for display."""
    insights_fqn = get_fully_qualified_name("AGENT_INSIGHTS")

    rows = session.sql(f"""
        SELECT * FROM {insights_fqn}
        ORDER BY CREATED_AT DESC
        LIMIT {limit}
    """).collect()

    return [dict(row) for row in rows]


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="ML Model Monitoring")
    parser.add_argument("--use-agent", action="store_true",
                        help="Use Cortex Agent for synthesis (requires setup.sql agent creation)")
    parser.add_argument("--create-agent", action="store_true",
                        help="Create/recreate the monitoring Cortex Agent")
    parser.add_argument("--query", type=str,
                        help="Ask the monitoring agent a question")
    args = parser.parse_args()

    session = create_session()
    print(f"Connected: {session.get_current_account()}")

    if args.create_agent:
        create_monitoring_agent(session)
    elif args.query:
        response = query_monitoring_agent(session, args.query)
        print(response)
    else:
        run_monitoring_cycle(session, use_agent=args.use_agent)
