-- =============================================================================
-- 02_feature_pipeline.sql — Dynamic Tables for feature aggregation
-- REDESIGNED: Richer behavioral features for investigation stories
-- =============================================================================

USE WAREHOUSE FRAUD_DEMO_WH;
USE DATABASE FRAUD_DETECTION_DEMO;

-- =============================================================================
-- CURATED.TRANSACTIONS_ENRICHED (INCREMENTAL)
-- =============================================================================
CREATE OR REPLACE DYNAMIC TABLE CURATED.TRANSACTIONS_ENRICHED
    TARGET_LAG = '5 minutes'
    WAREHOUSE = FRAUD_DEMO_WH
    REFRESH_MODE = INCREMENTAL
AS
SELECT
    t.TRANSACTION_ID,
    t.CUSTOMER_ID,
    t.MERCHANT_ID,
    t.TRANSACTION_AMOUNT,
    t.TRANSACTION_TIMESTAMP,
    t.CHANNEL,
    t.TRANSACTION_TYPE,
    t.CURRENCY,
    t.IS_INTERNATIONAL,
    t.TRANSACTION_LAT,
    t.TRANSACTION_LON,
    t.DEVICE_TYPE,
    t.IS_FRAUD,
    t.FRAUD_PATTERN,
    -- Customer context
    c.ADDRESS_CITY AS CUSTOMER_CITY,
    c.ADDRESS_STATE AS CUSTOMER_STATE,
    c.HOME_LAT,
    c.HOME_LON,
    c.ACCOUNT_OPEN_DATE,
    c.ACCOUNT_STATUS,
    c.RISK_TIER,
    c.CREDIT_LIMIT,
    c.CUSTOMER_SEGMENT,
    -- Merchant context
    m.CATEGORY AS MERCHANT_CATEGORY,
    m.RISK_SCORE AS MERCHANT_RISK_SCORE,
    m.COUNTRY AS MERCHANT_COUNTRY,
    m.IS_HIGH_RISK AS MERCHANT_IS_HIGH_RISK,
    m.DAYS_ACTIVE AS MERCHANT_DAYS_ACTIVE,
    -- Derived: distance from home (haversine km)
    ROUND(
        6371 * ACOS(
            LEAST(1, GREATEST(-1,
                COS(RADIANS(c.HOME_LAT)) * COS(RADIANS(t.TRANSACTION_LAT))
                * COS(RADIANS(t.TRANSACTION_LON) - RADIANS(c.HOME_LON))
                + SIN(RADIANS(c.HOME_LAT)) * SIN(RADIANS(t.TRANSACTION_LAT))
            ))
        ), 2
    ) AS DISTANCE_FROM_HOME_KM,
    -- Derived: account age
    DATEDIFF('day', c.ACCOUNT_OPEN_DATE, t.TRANSACTION_TIMESTAMP::DATE) AS ACCOUNT_AGE_DAYS,
    -- Derived: time features
    HOUR(t.TRANSACTION_TIMESTAMP) AS TRANSACTION_HOUR,
    DAYOFWEEK(t.TRANSACTION_TIMESTAMP) AS TRANSACTION_DOW,
    CASE WHEN HOUR(t.TRANSACTION_TIMESTAMP) >= 22 OR HOUR(t.TRANSACTION_TIMESTAMP) < 6
         THEN TRUE ELSE FALSE END AS IS_NIGHT_TRANSACTION,
    -- Derived: amount relative to credit
    CASE WHEN c.CREDIT_LIMIT > 0
         THEN ROUND(t.TRANSACTION_AMOUNT / c.CREDIT_LIMIT, 4)
         ELSE 0 END AS AMOUNT_TO_CREDIT_RATIO
FROM RAW.TRANSACTIONS t
LEFT JOIN RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN RAW.MERCHANTS m ON t.MERCHANT_ID = m.MERCHANT_ID;

-- =============================================================================
-- CURATED.CUSTOMER_FEATURE_BASE (FULL refresh)
-- Per-customer aggregates with richer behavioral signals
-- =============================================================================
CREATE OR REPLACE DYNAMIC TABLE CURATED.CUSTOMER_FEATURE_BASE
    TARGET_LAG = '5 minutes'
    WAREHOUSE = FRAUD_DEMO_WH
    REFRESH_MODE = FULL
AS
WITH txn_window AS (
    SELECT
        CUSTOMER_ID,
        TRANSACTION_AMOUNT,
        TRANSACTION_TIMESTAMP,
        CHANNEL,
        TRANSACTION_TYPE,
        CURRENCY,
        IS_INTERNATIONAL,
        MERCHANT_ID,
        MERCHANT_CATEGORY,
        MERCHANT_IS_HIGH_RISK,
        MERCHANT_DAYS_ACTIVE,
        DISTANCE_FROM_HOME_KM,
        IS_NIGHT_TRANSACTION,
        TRANSACTION_DOW,
        AMOUNT_TO_CREDIT_RATIO,
        DEVICE_TYPE,
        IS_FRAUD,
        -- Time windows
        CASE WHEN TRANSACTION_TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP()) THEN 1 ELSE 0 END AS IN_1H,
        CASE WHEN TRANSACTION_TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP()) THEN 1 ELSE 0 END AS IN_24H,
        CASE WHEN TRANSACTION_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP()) THEN 1 ELSE 0 END AS IN_7D,
        CASE WHEN TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_TIMESTAMP()) THEN 1 ELSE 0 END AS IN_30D,
        CASE WHEN TRANSACTION_TIMESTAMP < DATEADD('day', -7, CURRENT_TIMESTAMP())
             AND TRANSACTION_TIMESTAMP >= DATEADD('day', -37, CURRENT_TIMESTAMP()) THEN 1 ELSE 0 END AS IN_PRIOR_7D
    FROM CURATED.TRANSACTIONS_ENRICHED
)
SELECT
    CUSTOMER_ID,

    -- === VELOCITY FEATURES ===
    SUM(IN_1H) AS VELOCITY_1H,
    SUM(IN_24H) AS VELOCITY_24H,
    SUM(IN_7D) AS VELOCITY_7D,
    SUM(IN_30D) AS VELOCITY_30D,

    -- Velocity CHANGE: compare current 7d to prior 7d (behavioral shift detection)
    CASE WHEN SUM(IN_PRIOR_7D) > 0
         THEN (SUM(IN_7D)::FLOAT - SUM(IN_PRIOR_7D)) / SUM(IN_PRIOR_7D)
         ELSE CASE WHEN SUM(IN_7D) > 0 THEN 5.0 ELSE 0 END  -- new activity = high change
    END AS VELOCITY_CHANGE_RATIO,

    -- === AMOUNT FEATURES ===
    COALESCE(SUM(CASE WHEN IN_24H = 1 THEN TRANSACTION_AMOUNT END), 0) AS TOTAL_AMOUNT_24H,
    COALESCE(AVG(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END), 0) AS AVG_AMOUNT_7D,
    COALESCE(MAX(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END), 0) AS MAX_AMOUNT_7D,
    COALESCE(STDDEV(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END), 0) AS AMOUNT_STDDEV_7D,

    -- Max-to-avg ratio (spikiness indicator)
    CASE WHEN AVG(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END) > 0
         THEN MAX(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END)
              / AVG(CASE WHEN IN_7D = 1 THEN TRANSACTION_AMOUNT END)
         ELSE 0 END AS MAX_TO_AVG_RATIO_7D,

    -- === MERCHANT/BEHAVIORAL FEATURES ===
    COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN MERCHANT_ID END) AS UNIQUE_MERCHANTS_7D,

    -- New merchant ratio: % of 7d merchants never seen in prior 30d
    CASE WHEN COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN MERCHANT_ID END) > 0
         THEN (
             COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN MERCHANT_ID END)
             - COUNT(DISTINCT CASE WHEN IN_7D = 1 AND MERCHANT_ID IN (
                 SELECT DISTINCT MERCHANT_ID FROM CURATED.TRANSACTIONS_ENRICHED te2
                 WHERE te2.CUSTOMER_ID = txn_window.CUSTOMER_ID
                 AND te2.TRANSACTION_TIMESTAMP < DATEADD('day', -7, CURRENT_TIMESTAMP())
                 AND te2.TRANSACTION_TIMESTAMP >= DATEADD('day', -37, CURRENT_TIMESTAMP())
             ) THEN MERCHANT_ID END)
         )::FLOAT / COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN MERCHANT_ID END)
         ELSE 0
    END AS NEW_MERCHANT_RATIO_7D,

    -- High-risk merchant percentage
    COALESCE(AVG(CASE WHEN IN_7D = 1 THEN MERCHANT_IS_HIGH_RISK::INT END), 0) AS PCT_HIGH_RISK_MERCHANT_7D,

    -- Young merchant interaction (merchants active < 30 days)
    COALESCE(AVG(CASE WHEN IN_7D = 1 AND MERCHANT_DAYS_ACTIVE < 30 THEN 1 ELSE 0 END), 0) AS PCT_NEW_MERCHANTS_7D,

    -- === GEO FEATURES ===
    COALESCE(MAX(CASE WHEN IN_24H = 1 THEN DISTANCE_FROM_HOME_KM END), 0) AS GEO_SPREAD_24H,
    COALESCE(AVG(CASE WHEN IN_7D = 1 THEN DISTANCE_FROM_HOME_KM END), 0) AS AVG_DISTANCE_FROM_HOME_7D,
    COALESCE(AVG(CASE WHEN IN_7D = 1 THEN IS_INTERNATIONAL::INT END), 0) AS PCT_INTERNATIONAL_7D,

    -- Cross-border velocity: distinct countries in 7d
    COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN CURRENCY END) AS DISTINCT_CURRENCIES_7D,

    -- === TEMPORAL FEATURES ===
    COALESCE(AVG(CASE WHEN IN_7D = 1 THEN IS_NIGHT_TRANSACTION::INT END), 0) AS PCT_NIGHT_TXNS_7D,
    COALESCE(AVG(CASE WHEN IN_7D = 1 AND TRANSACTION_DOW IN (0, 6) THEN 1 ELSE 0 END), 0) AS PCT_WEEKEND_7D,

    -- === CHANNEL/DEVICE FEATURES ===
    COUNT(DISTINCT CASE WHEN IN_7D = 1 THEN CHANNEL END) AS CHANNEL_DIVERSITY_7D,
    COUNT(DISTINCT CASE WHEN IN_24H = 1 THEN DEVICE_TYPE END) AS DEVICE_SWITCH_COUNT_24H,

    -- === REFUND FEATURES ===
    COALESCE(
        SUM(CASE WHEN IN_7D = 1 AND TRANSACTION_TYPE = 'REFUND' THEN 1 ELSE 0 END)::FLOAT
        / NULLIF(SUM(CASE WHEN IN_7D = 1 AND TRANSACTION_TYPE = 'PURCHASE' THEN 1 ELSE 0 END), 0),
        0
    ) AS REFUND_TO_PURCHASE_RATIO_7D,

    -- === CREDIT UTILIZATION ===
    COALESCE(MAX(CASE WHEN IN_7D = 1 THEN AMOUNT_TO_CREDIT_RATIO END), 0) AS MAX_AMOUNT_TO_CREDIT_RATIO_7D,

    -- === DORMANCY: days since last txn before current 7d window ===
    COALESCE(
        DATEDIFF('day',
            MAX(CASE WHEN IN_PRIOR_7D = 1 THEN TRANSACTION_TIMESTAMP END),
            DATEADD('day', -7, CURRENT_TIMESTAMP())
        ), 30  -- default: assume 30 days dormant if no prior activity
    ) AS DORMANCY_DAYS_BEFORE_CURRENT,

    -- === LABEL (softened: any fraud in 7d, but diluted by mixed transactions) ===
    MAX(IS_FRAUD::INT) AS IS_FRAUD_LABEL

FROM txn_window
GROUP BY CUSTOMER_ID;
