-- Marketing Command Center Semantic View
-- Covers: demand forecasts, customer scores, POS actuals, customer transactions

CREATE SCHEMA IF NOT EXISTS SB_COMMAND_CENTER.SEMANTIC;

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
  'SB_COMMAND_CENTER.SEMANTIC',
  $$
name: MARKETING_COMMAND_CENTER_SV
description: >
  Unified analytics view for Summit Brands marketing team.
  Covers demand forecasts, customer propensity scores, POS sell-through actuals,
  and omnichannel customer transactions.

tables:
  - name: DEMAND_FORECASTS
    base_table:
      database: SB_COMMAND_CENTER
      schema: SCORING
      table: DEMAND_FORECASTS
    description: 8-week demand forecasts by retailer and brand, generated by XGBoost MMT models
    dimensions:
      - name: RETAILER_NAME
        description: Retail partner name (Walmart, Target, Ulta, Home Depot, Kohls)
        synonyms: [retailer, store, account, channel]
        expr: RETAILER_NAME
        data_type: VARCHAR
      - name: ITEM_BRAND
        description: Summit Brands brand (Peak Hydro, ChefLine, Ridgeline, VitaCare, PrimeLine)
        synonyms: [brand, product brand]
        expr: ITEM_BRAND
        data_type: VARCHAR
      - name: RETAILER_BRAND_KEY
        description: Partition key combining retailer and brand
        expr: RETAILER_BRAND_KEY
        data_type: VARCHAR
      - name: FORECAST_DATE
        description: Date of the forecast prediction
        synonyms: [prediction date, forecast week]
        expr: FORECAST_DATE
        data_type: DATE
      - name: WEEKS_AHEAD
        description: How many weeks ahead this forecast is (1-8)
        expr: WEEKS_AHEAD
        data_type: NUMBER
      - name: MODEL_VERSION
        description: Model training version identifier
        expr: MODEL_VERSION
        data_type: VARCHAR
    facts:
      - name: FORECASTED_UNITS
        description: Predicted unit sell-through for that week
        synonyms: [predicted units, forecast volume, expected sales]
        expr: FORECASTED_UNITS
        data_type: NUMBER
    metrics:
      - name: total_forecasted_units
        description: Sum of forecasted unit sales
        expr: SUM(DEMAND_FORECASTS.FORECASTED_UNITS)
        synonyms: [predicted volume, forecast total]

  - name: CUSTOMER_SCORES
    base_table:
      database: SB_COMMAND_CENTER
      schema: SCORING
      table: CUSTOMER_SCORES
    description: Customer propensity scores and segment assignments from ML models
    primary_key:
      columns: [CUSTOMER_ID]
    dimensions:
      - name: CUSTOMER_ID
        description: Unique customer identifier
        expr: CUSTOMER_ID
        data_type: VARCHAR
      - name: SEGMENT_LABEL
        description: Customer segment (Champion, Engaged, Moderate, At Risk)
        synonyms: [segment, customer tier, customer group]
        expr: SEGMENT_LABEL
        data_type: VARCHAR
      - name: SCORED_AT
        description: When the scores were last computed
        expr: SCORED_AT
        data_type: TIMESTAMP
    facts:
      - name: REPURCHASE_SCORE
        description: Probability (0-1) that customer will repurchase within 90 days
        synonyms: [propensity score, repurchase probability, likelihood to buy]
        expr: REPURCHASE_SCORE
        data_type: FLOAT
      - name: LTV_PREDICTION
        description: Predicted next-12-month customer lifetime value in dollars
        synonyms: [lifetime value, predicted spend, CLV, customer value]
        expr: LTV_PREDICTION
        data_type: FLOAT
    metrics:
      - name: avg_repurchase_score
        description: Average repurchase propensity across customers
        expr: AVG(CUSTOMER_SCORES.REPURCHASE_SCORE)
      - name: customer_count_by_segment
        description: Number of customers in each segment
        expr: COUNT(DISTINCT CUSTOMER_SCORES.CUSTOMER_ID)

  - name: POS_SALES
    base_table:
      database: SB_COMMAND_CENTER
      schema: RAW
      table: POS_SALES
    description: Weekly point-of-sale actuals from retail partners at store/brand/week level
    dimensions:
      - name: RETAILER_NAME
        description: Retail partner name
        synonyms: [retailer, store chain, account]
        expr: RETAILER_NAME
        data_type: VARCHAR
      - name: ITEM_BRAND
        description: Summit Brands brand name
        synonyms: [brand]
        expr: ITEM_BRAND
        data_type: VARCHAR
      - name: RETAILER_DATE
        description: Week-ending date for POS reporting
        synonyms: [week, sales week, pos date]
        expr: RETAILER_DATE
        data_type: DATE
      - name: STORE_NUMBER
        description: Individual store identifier within retailer
        expr: STORE_NUMBER
        data_type: VARCHAR
    facts:
      - name: GROSS_AMT_SOLD_UNITS
        description: Gross units sold at store level
        synonyms: [units sold, volume, quantity sold]
        expr: GROSS_AMT_SOLD_UNITS
        data_type: NUMBER
      - name: GROSS_SALES_RETAIL
        description: Gross sales revenue at retail price
        synonyms: [revenue, sales dollars, gross revenue]
        expr: GROSS_SALES_RETAIL
        data_type: NUMBER
      - name: NET_SALES_RETAIL
        description: Net sales after returns at retail price
        synonyms: [net revenue, net sales]
        expr: NET_SALES_RETAIL
        data_type: NUMBER
      - name: NET_SALES_UNITS
        description: Net units sold after returns
        expr: NET_SALES_UNITS
        data_type: NUMBER
      - name: CUSTOMER_RETURN_UNITS
        description: Units returned by customers
        synonyms: [returns, return volume]
        expr: CUSTOMER_RETURN_UNITS
        data_type: NUMBER
      - name: INVENTORY_UNITS
        description: On-hand inventory units at store
        synonyms: [stock, inventory, on hand]
        expr: INVENTORY_UNITS
        data_type: NUMBER
      - name: ON_ORDER_QUANTITY
        description: Units on order not yet received
        synonyms: [on order, pipeline]
        expr: ON_ORDER_QUANTITY
        data_type: NUMBER
      - name: TOTAL_MARKDOWN
        description: Total markdown/discount amount applied
        synonyms: [markdowns, discounts, promotions]
        expr: TOTAL_MARKDOWN
        data_type: NUMBER
      - name: UNIT_PRICE
        description: Selling price per unit
        expr: UNIT_PRICE
        data_type: NUMBER
    metrics:
      - name: total_pos_sales
        description: Total POS sell-through revenue
        expr: SUM(POS_SALES.GROSS_SALES_RETAIL)
        synonyms: [total revenue, gross sales]
      - name: total_pos_units
        description: Total POS units sold
        expr: SUM(POS_SALES.GROSS_AMT_SOLD_UNITS)
        synonyms: [total units, total volume]

  - name: CUSTOMER_TRANSACTIONS
    base_table:
      database: SB_COMMAND_CENTER
      schema: RAW
      table: CUSTOMER_TRANSACTIONS
    description: Omnichannel customer transaction history (DTC, web, in-store)
    primary_key:
      columns: [TRANSACTION_ID]
    dimensions:
      - name: CUSTOMER_ID
        description: Unique customer identifier
        expr: CUSTOMER_ID
        data_type: VARCHAR
      - name: TRANSACTION_ID
        description: Unique transaction identifier
        expr: TRANSACTION_ID
        data_type: VARCHAR
      - name: TRANSACTION_DATE
        description: Date and time of purchase
        synonyms: [purchase date, order date]
        expr: TRANSACTION_DATE
        data_type: TIMESTAMP
      - name: BRAND
        description: Brand purchased
        synonyms: [product brand]
        expr: BRAND
        data_type: VARCHAR
      - name: STATE
        description: Customer state/region
        synonyms: [region, geography, location]
        expr: STATE
        data_type: VARCHAR
      - name: DISCOUNT_OFFER_APPLIED
        description: Coupon or discount code used (NULL if none)
        synonyms: [coupon, promo code, discount]
        expr: DISCOUNT_OFFER_APPLIED
        data_type: VARCHAR
      - name: PROREWARDS_CUSTOMER
        description: Whether customer is a ProRewards (employee/partner) member (Y/N)
        synonyms: [prorewards, employee discount, partner]
        expr: PROREWARDS_CUSTOMER
        data_type: VARCHAR
    facts:
      - name: PURCHASE_AMOUNT
        description: Transaction amount in dollars
        synonyms: [order value, spend, amount]
        expr: PURCHASE_AMOUNT
        data_type: NUMBER
      - name: ORDERED_UNITS
        description: Number of units purchased
        synonyms: [quantity, items]
        expr: ORDERED_UNITS
        data_type: NUMBER

relationships:
  - left_table: CUSTOMER_TRANSACTIONS
    right_table: CUSTOMER_SCORES
    relationship_columns:
      - left_column: CUSTOMER_ID
        right_column: CUSTOMER_ID
    relationship_type: many_to_one
  $$
);
