-- 04_flatten_and_score.sql
-- Flattens the AI_COMPLETE JSON into PACKING_SLIP_HEADERS and LINE_ITEMS,
-- then runs confidence scoring and sets review statuses.
USE SCHEMA PACKING_SLIP_PROCESSING.PACKING_SLIPS;

-- Flatten headers
INSERT INTO PACKING_SLIP_HEADERS (
    EXTRACTION_ID, SLIP_INDEX, FILE_NAME, PAGE_NUMBER, PAGE_FILE,
    PO_NUMBER, SUPPLIER_NAME, SHIPMENT_NUMBER, SHIPMENT_DATE,
    SHIP_TO_ADDRESS, BILL_TO_ADDRESS, CARRIER, TRACKING_NUMBER,
    RECEIVED_DATE, RECEIVED_BY
)
SELECT
    e.EXTRACTION_ID,
    f.INDEX,
    e.FILE_NAME,
    f.VALUE:approximate_page::NUMBER,
    e.FILE_NAME,
    f.VALUE:po_number::VARCHAR,
    f.VALUE:supplier_name::VARCHAR,
    f.VALUE:shipment_number::VARCHAR,
    f.VALUE:shipment_date::VARCHAR,
    f.VALUE:ship_to_address::VARCHAR,
    f.VALUE:bill_to_address::VARCHAR,
    f.VALUE:carrier::VARCHAR,
    f.VALUE:tracking_number::VARCHAR,
    f.VALUE:received_date::VARCHAR,
    f.VALUE:received_by::VARCHAR
FROM AI_COMPLETE_EXTRACTIONS e,
    LATERAL FLATTEN(input => e.PARSED_JSON) f
WHERE e.EXTRACTION_ID NOT IN (SELECT DISTINCT EXTRACTION_ID FROM PACKING_SLIP_HEADERS WHERE EXTRACTION_ID IS NOT NULL);

-- Flatten line items linked to headers
INSERT INTO PACKING_SLIP_LINE_ITEMS (
    HEADER_ID, PART_NUMBER, DESCRIPTION, QUANTITY_ORDERED, QUANTITY_SHIPPED, UNIT_OF_MEASURE
)
SELECT
    h.HEADER_ID,
    li.VALUE:part_number::VARCHAR,
    li.VALUE:description::VARCHAR,
    li.VALUE:quantity_ordered::VARCHAR,
    li.VALUE:quantity_shipped::VARCHAR,
    li.VALUE:unit_of_measure::VARCHAR
FROM AI_COMPLETE_EXTRACTIONS ext
CROSS JOIN LATERAL FLATTEN(input => ext.PARSED_JSON) slip
CROSS JOIN LATERAL FLATTEN(input => slip.VALUE:line_items) li
JOIN PACKING_SLIP_HEADERS h
    ON h.EXTRACTION_ID = ext.EXTRACTION_ID AND h.SLIP_INDEX = slip.INDEX
WHERE h.HEADER_ID NOT IN (SELECT DISTINCT HEADER_ID FROM PACKING_SLIP_LINE_ITEMS WHERE HEADER_ID IS NOT NULL);

-- Confidence scoring
UPDATE PACKING_SLIP_HEADERS h
SET CONFIDENCE_SCORE = (
    (CASE WHEN h.PO_NUMBER IS NOT NULL AND h.PO_NUMBER != '' THEN 1 ELSE 0 END
    + CASE WHEN h.SUPPLIER_NAME IS NOT NULL AND h.SUPPLIER_NAME != '' THEN 1 ELSE 0 END
    + CASE WHEN h.SHIPMENT_DATE IS NOT NULL AND h.SHIPMENT_DATE != '' THEN 1 ELSE 0 END
    + CASE WHEN h.SHIP_TO_ADDRESS IS NOT NULL AND h.SHIP_TO_ADDRESS != '' THEN 1 ELSE 0 END
    + CASE WHEN h.CARRIER IS NOT NULL AND h.CARRIER != '' THEN 1 ELSE 0 END
    + CASE WHEN h.TRACKING_NUMBER IS NOT NULL AND h.TRACKING_NUMBER != '' THEN 1 ELSE 0 END
    ) / 6.0 * 0.50
    + CASE WHEN h.PO_NUMBER IS NOT NULL AND REGEXP_LIKE(h.PO_NUMBER, '^[A-Za-z0-9][A-Za-z0-9\\-]{3,}$') THEN 0.20 ELSE 0.05 END
    + CASE WHEN TRY_TO_DATE(h.SHIPMENT_DATE) IS NOT NULL THEN 0.15 ELSE 0.03 END
    + CASE WHEN EXISTS (
        SELECT 1 FROM PACKING_SLIP_LINE_ITEMS li WHERE li.HEADER_ID = h.HEADER_ID AND li.PART_NUMBER IS NOT NULL
    ) THEN 0.15 ELSE 0 END
)
WHERE h.REVIEW_STATUS = 'PENDING';

-- Set review statuses based on confidence
UPDATE PACKING_SLIP_HEADERS
SET REVIEW_STATUS = CASE
    WHEN CONFIDENCE_SCORE >= (SELECT CONFIG_VALUE::FLOAT FROM PIPELINE_CONFIG WHERE CONFIG_KEY = 'auto_approve_threshold')
        THEN 'AUTO_APPROVED'
    WHEN CONFIDENCE_SCORE < (SELECT CONFIG_VALUE::FLOAT FROM PIPELINE_CONFIG WHERE CONFIG_KEY = 'needs_review_threshold')
        THEN 'NEEDS_REVIEW'
    ELSE 'PENDING'
END
WHERE REVIEW_STATUS = 'PENDING';

-- Spot-check: randomly flag some AUTO_APPROVED for review
UPDATE PACKING_SLIP_HEADERS
SET REVIEW_STATUS = 'SPOT_CHECK'
WHERE REVIEW_STATUS = 'AUTO_APPROVED'
AND UNIFORM(0::FLOAT, 100::FLOAT, RANDOM()) < (SELECT CONFIG_VALUE::FLOAT FROM PIPELINE_CONFIG WHERE CONFIG_KEY = 'spot_check_pct');

-- Verify
SELECT REVIEW_STATUS, COUNT(*) AS CNT, ROUND(AVG(CONFIDENCE_SCORE), 2) AS AVG_CONF
FROM PACKING_SLIP_HEADERS GROUP BY 1 ORDER BY CNT DESC;

SELECT 'Headers' AS TBL, COUNT(*) AS CNT FROM PACKING_SLIP_HEADERS
UNION ALL SELECT 'Line Items', COUNT(*) FROM PACKING_SLIP_LINE_ITEMS;
