-- 07_reconciliation_view.sql
-- Reconciliation view: joins shipped packing slip data against PO data.
-- Detects missing POs, quantity mismatches, unknown parts, and duplicate shipments.
USE SCHEMA PACKING_SLIP_PROCESSING.PACKING_SLIPS;

CREATE OR REPLACE VIEW RECONCILIATION_VIEW AS
WITH shipped_data AS (
    SELECT
        h.HEADER_ID,
        h.PO_NUMBER,
        h.SUPPLIER_NAME AS SHIPPED_SUPPLIER,
        h.SHIPMENT_DATE,
        h.FILE_NAME,
        h.REVIEW_STATUS AS HEADER_REVIEW_STATUS,
        li.LINE_ITEM_ID,
        li.PART_NUMBER AS SHIPPED_PART_NUMBER,
        li.DESCRIPTION AS SHIPPED_DESCRIPTION,
        TRY_CAST(li.QUANTITY_ORDERED AS NUMBER) AS SHIPPED_QTY_ORDERED,
        TRY_CAST(li.QUANTITY_SHIPPED AS NUMBER) AS SHIPPED_QTY_SHIPPED,
        TRY_CAST(li.BACK_ORDERED AS NUMBER) AS SHIPPED_BACK_ORDERED
    FROM PACKING_SLIP_HEADERS h
    LEFT JOIN PACKING_SLIP_LINE_ITEMS li ON h.HEADER_ID = li.HEADER_ID
    WHERE h.PO_NUMBER IS NOT NULL
),
po_data AS (
    SELECT
        po.PO_ID,
        po.PO_NUMBER,
        po.SUPPLIER_NAME AS PO_SUPPLIER,
        po.ORDER_DATE,
        po.EXPECTED_DELIVERY_DATE,
        pl.PO_LINE_ID,
        pl.PART_NUMBER AS PO_PART_NUMBER,
        pl.DESCRIPTION AS PO_DESCRIPTION,
        pl.QUANTITY_ORDERED AS PO_QTY_ORDERED,
        pl.UNIT_PRICE
    FROM PURCHASE_ORDERS po
    LEFT JOIN PO_LINE_ITEMS pl ON po.PO_ID = pl.PO_ID
),
reconciled AS (
    SELECT
        COALESCE(s.PO_NUMBER, p.PO_NUMBER) AS PO_NUMBER,
        s.HEADER_ID,
        s.SHIPPED_SUPPLIER,
        s.SHIPMENT_DATE,
        s.FILE_NAME,
        s.HEADER_REVIEW_STATUS,
        s.LINE_ITEM_ID,
        s.SHIPPED_PART_NUMBER,
        s.SHIPPED_DESCRIPTION,
        s.SHIPPED_QTY_ORDERED,
        s.SHIPPED_QTY_SHIPPED,
        s.SHIPPED_BACK_ORDERED,
        p.PO_ID,
        p.PO_SUPPLIER,
        p.ORDER_DATE,
        p.EXPECTED_DELIVERY_DATE,
        p.PO_LINE_ID,
        p.PO_PART_NUMBER,
        p.PO_DESCRIPTION,
        p.PO_QTY_ORDERED,
        p.UNIT_PRICE,
        CASE WHEN s.PO_NUMBER IS NOT NULL AND p.PO_ID IS NULL THEN TRUE ELSE FALSE END AS FLAG_MISSING_PO,
        CASE WHEN s.SHIPPED_QTY_SHIPPED IS NOT NULL AND p.PO_QTY_ORDERED IS NOT NULL
             AND s.SHIPPED_QTY_SHIPPED != p.PO_QTY_ORDERED THEN TRUE ELSE FALSE END AS FLAG_QTY_MISMATCH,
        CASE WHEN s.SHIPPED_PART_NUMBER IS NOT NULL AND s.PO_NUMBER IS NOT NULL
             AND p.PO_ID IS NOT NULL AND p.PO_PART_NUMBER IS NULL THEN TRUE ELSE FALSE END AS FLAG_UNKNOWN_PART,
        CASE WHEN s.SHIPPED_QTY_SHIPPED IS NOT NULL AND p.PO_QTY_ORDERED IS NOT NULL
             THEN s.SHIPPED_QTY_SHIPPED - p.PO_QTY_ORDERED ELSE NULL END AS QTY_DIFFERENCE
    FROM shipped_data s
    FULL OUTER JOIN po_data p
        ON s.PO_NUMBER = p.PO_NUMBER
        AND s.SHIPPED_PART_NUMBER = p.PO_PART_NUMBER
),
dup_check AS (
    SELECT
        PO_NUMBER,
        SHIPPED_PART_NUMBER,
        COUNT(DISTINCT HEADER_ID) AS SHIPMENT_COUNT
    FROM shipped_data
    WHERE SHIPPED_PART_NUMBER IS NOT NULL
    GROUP BY PO_NUMBER, SHIPPED_PART_NUMBER
    HAVING COUNT(DISTINCT HEADER_ID) > 1
)
SELECT
    r.*,
    CASE WHEN d.SHIPMENT_COUNT > 1 THEN TRUE ELSE FALSE END AS FLAG_DUPLICATE_SHIPMENT,
    COALESCE(d.SHIPMENT_COUNT, 1) AS TOTAL_SHIPMENTS_FOR_PART,
    CASE WHEN r.FLAG_MISSING_PO OR r.FLAG_QTY_MISMATCH OR r.FLAG_UNKNOWN_PART
         OR COALESCE(d.SHIPMENT_COUNT, 1) > 1 THEN TRUE ELSE FALSE END AS HAS_ISSUES
FROM reconciled r
LEFT JOIN dup_check d
    ON r.PO_NUMBER = d.PO_NUMBER
    AND r.SHIPPED_PART_NUMBER = d.SHIPPED_PART_NUMBER;
