1... server {
2...     listen 80;
3...     root /usr/share/nginx/html;
4...     index index.html;
5... 
6...     location / {
7...         try_files $uri $uri/ /index.html;
8...     }
9... 
10...     location /api/ {
11...         proxy_pass http://127.0.0.1:3001;
12...         proxy_set_header Host $host;
13...         proxy_set_header Sf-Context-Current-User-Token $http_sf_context_current_user_token;
14...         proxy_read_timeout 120s;
15...     }
16... }
17... 