-- =============================================================================
-- Schema Mapper Agent — Seed Reference Data
-- Realistic reference data for expense management ingestion.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ACME_FINANCE.INGESTION;
USE SCHEMA ACME_FINANCE.INGESTION;

-- ── Departments ──────────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_DEPARTMENTS;
INSERT INTO REF_DEPARTMENTS (department_name) VALUES
    ('Accounting'),
    ('Business Development'),
    ('Construction'),
    ('Customer Success'),
    ('Engineering'),
    ('Executive'),
    ('Facilities'),
    ('Field Operations'),
    ('Finance'),
    ('Fleet Pool'),
    ('HR'),
    ('IT'),
    ('Inspections'),
    ('Legal'),
    ('Logistics'),
    ('Maintenance'),
    ('Manufacturing'),
    ('Marketing'),
    ('Operations'),
    ('Procurement'),
    ('Product'),
    ('Property Management'),
    ('Quality Assurance'),
    ('R&D'),
    ('Sales'),
    ('Service Delivery'),
    ('Supply Chain'),
    ('Warehouse');

-- ── GL Accounts ──────────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_GL_ACCOUNTS;
INSERT INTO REF_GL_ACCOUNTS (gl_account_code, gl_account_name) VALUES
    ('5100', 'Travel & Transportation'),
    ('5110', 'Mileage Reimbursement'),
    ('5120', 'Airfare'),
    ('5130', 'Ground Transportation'),
    ('5140', 'Lodging'),
    ('5200', 'Office Supplies'),
    ('5210', 'Computer Equipment'),
    ('5220', 'Software Subscriptions'),
    ('5230', 'Printing & Reproduction'),
    ('5300', 'Meals & Entertainment'),
    ('5310', 'Client Entertainment'),
    ('5320', 'Team Meals'),
    ('5400', 'Professional Services'),
    ('5410', 'Legal Fees'),
    ('5420', 'Consulting Fees'),
    ('5430', 'Audit & Tax'),
    ('5500', 'Facilities & Utilities'),
    ('5510', 'Rent'),
    ('5520', 'Utilities'),
    ('5530', 'Maintenance & Repairs'),
    ('5540', 'Janitorial'),
    ('5600', 'Insurance'),
    ('5700', 'Telecommunications'),
    ('5710', 'Mobile Phone'),
    ('5720', 'Internet & Data'),
    ('5800', 'Training & Development'),
    ('5810', 'Conferences'),
    ('5820', 'Certifications'),
    ('5900', 'Marketing & Advertising'),
    ('5910', 'Digital Advertising'),
    ('5920', 'Print Media'),
    ('5930', 'Events & Sponsorships'),
    ('6100', 'Vehicle Expenses'),
    ('6110', 'Fuel'),
    ('6120', 'Vehicle Maintenance'),
    ('6130', 'Vehicle Insurance'),
    ('6140', 'Tolls & Parking'),
    ('6200', 'Shipping & Postage'),
    ('6300', 'Dues & Memberships'),
    ('6400', 'Bank Fees & Charges'),
    ('6500', 'Depreciation'),
    ('6600', 'Cost of Goods Sold'),
    ('6700', 'Raw Materials'),
    ('6800', 'Contract Labor'),
    ('6900', 'Miscellaneous');

-- ── Expense Categories ───────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_EXPENSE_CATEGORIES;
INSERT INTO REF_EXPENSE_CATEGORIES (category_name) VALUES
    ('Advertising'),
    ('Airfare'),
    ('Bank Fees'),
    ('Car Rental'),
    ('Certifications'),
    ('Client Entertainment'),
    ('Computer Equipment'),
    ('Conferences'),
    ('Consulting'),
    ('Contract Labor'),
    ('Depreciation'),
    ('Digital Advertising'),
    ('Dues & Memberships'),
    ('Equipment Rental'),
    ('Events & Sponsorships'),
    ('Facilities Maintenance'),
    ('Fuel'),
    ('Ground Transportation'),
    ('Insurance'),
    ('Internet & Data'),
    ('Janitorial'),
    ('Legal Fees'),
    ('Lodging'),
    ('Meals - Business'),
    ('Meals - Team'),
    ('Mileage'),
    ('Mobile Phone'),
    ('Office Supplies'),
    ('Parking'),
    ('Postage & Shipping'),
    ('Printing'),
    ('Professional Development'),
    ('Raw Materials'),
    ('Rent'),
    ('Repairs'),
    ('Software'),
    ('Team Building'),
    ('Telecommunications'),
    ('Tolls'),
    ('Training'),
    ('Travel - Other'),
    ('Utilities'),
    ('Vehicle Insurance'),
    ('Vehicle Maintenance');

-- ── Payment Methods ──────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_PAYMENT_METHODS;
INSERT INTO REF_PAYMENT_METHODS (method_name) VALUES
    ('Corporate Amex'),
    ('Corporate Mastercard'),
    ('Corporate Visa'),
    ('ACH Transfer'),
    ('Wire Transfer'),
    ('Check'),
    ('Petty Cash'),
    ('Personal Card (Reimbursement)'),
    ('Purchase Order'),
    ('Direct Debit'),
    ('PayPal'),
    ('Virtual Card');

-- ── Currencies ───────────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_CURRENCIES;
INSERT INTO REF_CURRENCIES (currency_code) VALUES
    ('USD'),
    ('EUR'),
    ('GBP'),
    ('CAD'),
    ('AUD'),
    ('JPY'),
    ('CHF'),
    ('MXN'),
    ('BRL'),
    ('INR'),
    ('SGD'),
    ('HKD');

-- ── Cost Centers ─────────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_COST_CENTERS;
INSERT INTO REF_COST_CENTERS (cost_center_code, cost_center_name) VALUES
    ('CC-1000', 'Corporate HQ'),
    ('CC-1100', 'Executive Office'),
    ('CC-1200', 'Finance & Accounting'),
    ('CC-1300', 'Human Resources'),
    ('CC-1400', 'Legal & Compliance'),
    ('CC-2000', 'Sales - North America'),
    ('CC-2100', 'Sales - EMEA'),
    ('CC-2200', 'Sales - APAC'),
    ('CC-2300', 'Sales - LATAM'),
    ('CC-3000', 'Engineering'),
    ('CC-3100', 'Product Development'),
    ('CC-3200', 'Quality Assurance'),
    ('CC-3300', 'IT Infrastructure'),
    ('CC-4000', 'Marketing'),
    ('CC-4100', 'Digital Marketing'),
    ('CC-4200', 'Events & Conferences'),
    ('CC-5000', 'Operations'),
    ('CC-5100', 'Field Operations'),
    ('CC-5200', 'Logistics'),
    ('CC-5300', 'Supply Chain'),
    ('CC-6000', 'Manufacturing'),
    ('CC-6100', 'Warehouse'),
    ('CC-6200', 'Distribution'),
    ('CC-7000', 'Customer Success'),
    ('CC-7100', 'Support'),
    ('CC-7200', 'Professional Services'),
    ('CC-8000', 'Facilities'),
    ('CC-8100', 'Property Management'),
    ('CC-9000', 'R&D'),
    ('CC-9100', 'Innovation Lab');

-- ── Vendors ──────────────────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS REF_VENDORS;
INSERT INTO REF_VENDORS (vendor_name, vendor_id) VALUES
    ('Amazon Web Services', 'V-1001'),
    ('Microsoft', 'V-1002'),
    ('Google Cloud', 'V-1003'),
    ('Salesforce', 'V-1004'),
    ('Adobe Systems', 'V-1005'),
    ('Zoom Video Communications', 'V-1006'),
    ('Slack Technologies', 'V-1007'),
    ('Atlassian', 'V-1008'),
    ('Snowflake', 'V-1009'),
    ('Datadog', 'V-1010'),
    ('Okta', 'V-1011'),
    ('HubSpot', 'V-1012'),
    ('Twilio', 'V-1013'),
    ('Stripe', 'V-1014'),
    ('DocuSign', 'V-1015'),
    ('FedEx', 'V-2001'),
    ('UPS', 'V-2002'),
    ('DHL', 'V-2003'),
    ('Staples', 'V-3001'),
    ('Office Depot', 'V-3002'),
    ('Dell Technologies', 'V-3003'),
    ('Apple', 'V-3004'),
    ('Lenovo', 'V-3005'),
    ('WeWork', 'V-4001'),
    ('CBRE', 'V-4002'),
    ('JLL', 'V-4003'),
    ('Cushman & Wakefield', 'V-4004'),
    ('Marriott International', 'V-5001'),
    ('Hilton Hotels', 'V-5002'),
    ('United Airlines', 'V-5003'),
    ('Delta Air Lines', 'V-5004'),
    ('American Airlines', 'V-5005'),
    ('Hertz', 'V-5006'),
    ('Enterprise Rent-A-Car', 'V-5007'),
    ('Deloitte', 'V-6001'),
    ('PricewaterhouseCoopers', 'V-6002'),
    ('KPMG', 'V-6003'),
    ('Ernst & Young', 'V-6004'),
    ('Baker McKenzie', 'V-6005'),
    ('Gartner', 'V-6006'),
    ('McKinsey & Company', 'V-6007'),
    ('AT&T', 'V-7001'),
    ('Verizon', 'V-7002'),
    ('T-Mobile', 'V-7003'),
    ('Comcast', 'V-7004'),
    ('ADP', 'V-8001'),
    ('Workday', 'V-8002'),
    ('SAP', 'V-8003'),
    ('Oracle', 'V-8004'),
    ('ServiceNow', 'V-8005');